export interface Account {
  cta: string;
  description: string;
  type: 'Balance' | 'Resultados' | 'Registro';
  reqCenCos?: boolean;
  amarreDebe?: string;
  amarreHaber?: string;
}

export const INITIAL_PLAN: Account[] = [
  // ──── ACTIVO ────
  { cta: '10', description: 'EFECTIVO Y EQUIVALENTES DE EFECTIVO', type: 'Balance' },
  { cta: '101', description: 'Caja', type: 'Balance' },
  { cta: '1011', description: 'Caja Nacional', type: 'Balance' },
  { cta: '104', description: 'Cuentas corrientes en instituciones financieras', type: 'Balance' },
  { cta: '1041', description: 'Cuentas Corrientes Operativas', type: 'Balance' },
  { cta: '1042', description: 'Cuentas Corrientes para Fines Específicos', type: 'Balance' },
  { cta: '1091', description: 'Fondos Sujetos a Restricción', type: 'Balance' },
  { cta: '11', description: 'INVERSIONES FINANCIERAS', type: 'Balance' },
  { cta: '111', description: 'Valores al Costo', type: 'Balance' },
  { cta: '12', description: 'CUENTAS POR COBRAR COMERCIALES - TERCEROS', type: 'Balance' },
  { cta: '121', description: 'Facturas, boletas y otros comprobantes por cobrar', type: 'Balance' },
  { cta: '1211', description: 'No emitidas', type: 'Balance' },
  { cta: '12111', description: 'No emitidas - Moneda Nacional', type: 'Balance' },
  { cta: '1212', description: 'Emitidas en cartera', type: 'Balance' },
  { cta: '12121', description: 'Emitidas en cartera - Moneda Nacional', type: 'Balance' },
  { cta: '12122', description: 'Emitidas en cartera - Moneda Extranjera', type: 'Balance' },
  { cta: '1213', description: 'En cobranza', type: 'Balance' },
  { cta: '12131', description: 'En cobranza - Moneda Nacional', type: 'Balance' },
  { cta: '123', description: 'Letras por cobrar', type: 'Balance' },
  { cta: '1231', description: 'En cartera', type: 'Balance' },
  { cta: '1232', description: 'Anticipos Otorgados', type: 'Balance' },
  { cta: '14', description: 'CUENTAS POR COBRAR AL PERSONAL, ACCIONISTAS Y DIRECTORES', type: 'Balance' },
  { cta: '141', description: 'Personal', type: 'Balance' },
  { cta: '16', description: 'CUENTAS POR COBRAR DIVERSAS - TERCEROS', type: 'Balance' },
  { cta: '161', description: 'Préstamos a terceros', type: 'Balance' },
  { cta: '18', description: 'SERVICIOS Y OTROS CONTRATADOS POR ANTICIPADO', type: 'Balance' },
  { cta: '20', description: 'MERCADERÍAS', type: 'Balance' },
  { cta: '201', description: 'Mercaderías', type: 'Balance' },
  { cta: '2011', description: 'Mercaderías', type: 'Balance' },
  { cta: '21', description: 'PRODUCTOS TERMINADOS', type: 'Balance' },
  { cta: '24', description: 'MATERIAS PRIMAS', type: 'Balance' },
  { cta: '25', description: 'MATERIALES AUXILIARES, SUMINISTROS Y REPUESTOS', type: 'Balance' },
  { cta: '27', description: 'ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA', type: 'Balance' },
  { cta: '271', description: 'Activos No Corrientes Mantenidos para La Venta', type: 'Balance' },
  { cta: '30', description: 'INVERSIONES MOBILIARIAS', type: 'Balance' },
  { cta: '301', description: 'Inversiones Inmobiliarias', type: 'Balance' },
  { cta: '33', description: 'PROPIEDADES, PLANTA Y EQUIPO', type: 'Balance' },
  { cta: '331', description: 'Terrenos', type: 'Balance' },
  { cta: '332', description: 'Edificaciones', type: 'Balance' },
  { cta: '333', description: 'Maquinarias y equipos de explotación', type: 'Balance' },
  { cta: '334', description: 'Unidades de transporte', type: 'Balance' },
  { cta: '335', description: 'Muebles y enseres', type: 'Balance' },
  { cta: '336', description: 'Equipos diversos', type: 'Balance' },
  { cta: '337', description: 'Herramientas y unidades de reemplazo', type: 'Balance' },
  { cta: '338', description: 'Obras en curso', type: 'Balance' },
  { cta: '339', description: 'Depreciación y amortización', type: 'Balance' },
  { cta: '3391', description: 'Depreciación Acumulada', type: 'Balance' },
  { cta: '34', description: 'INTANGIBLES', type: 'Balance' },
  { cta: '341', description: 'Concesiones, Licencias y Otros Derechos', type: 'Balance' },
  { cta: '39', description: 'DEPRECIACIÓN Y AMORTIZACIÓN ACUMULADA', type: 'Balance' },
  { cta: '391', description: 'Depreciación acumulada', type: 'Balance' },
  { cta: '395', description: 'Depreciación acumulada de propiedad, planta y equipo', type: 'Balance' },
  { cta: '3952', description: 'Depreciación acumulada - Costo', type: 'Balance' },
  
  // ──── PASIVO ────
  { cta: '40', description: 'TRIBUTOS, CONTRAPRESTACIONES Y APORTES', type: 'Balance' },
  { cta: '401', description: 'Gobierno Central', type: 'Balance' },
  { cta: '4011', description: 'Impuesto general a las ventas', type: 'Balance' },
  { cta: '40111', description: 'IGV - Cuenta Propia', type: 'Balance' },
  { cta: '40112', description: 'IGV - Servicios / Ventas', type: 'Balance' },
  { cta: '40113', description: 'IGV - Régimen de Percepciones', type: 'Balance' },
  { cta: '40114', description: 'IGV - Régimen de Retenciones', type: 'Balance' },
  { cta: '4012', description: 'Impuesto Selectivo al Consumo', type: 'Balance' },
  { cta: '4017', description: 'Impuesto a la Renta', type: 'Balance' },
  { cta: '40171', description: 'Renta de Tercera Categoría', type: 'Balance' },
  { cta: '40172', description: 'Renta de Cuarta Categoría', type: 'Balance' },
  { cta: '40173', description: 'Renta de Quinta Categoría', type: 'Balance' },
  { cta: '403', description: 'Instituciones Públicas', type: 'Balance' },
  { cta: '4031', description: 'ESSALUD', type: 'Balance' },
  { cta: '4032', description: 'ONP', type: 'Balance' },
  { cta: '41', description: 'REMUNERACIONES Y PARTICIPACIONES POR PAGAR', type: 'Balance' },
  { cta: '411', description: 'Remuneraciones por Pagar', type: 'Balance' },
  { cta: '415', description: 'Beneficios Sociales de los Trabajadores por Pagar', type: 'Balance' },
  { cta: '42', description: 'CUENTAS POR PAGAR COMERCIALES - TERCEROS', type: 'Balance' },
  { cta: '421', description: 'Facturas, boletas y otros comprobantes por pagar', type: 'Balance' },
  { cta: '4211', description: 'No emitidas', type: 'Balance' },
  { cta: '42111', description: 'No emitidas - Moneda Nacional', type: 'Balance' },
  { cta: '4212', description: 'Emitidas', type: 'Balance' },
  { cta: '42121', description: 'Emitidas - Moneda Nacional', type: 'Balance' },
  { cta: '42122', description: 'Emitidas - Moneda Extranjera', type: 'Balance' },
  { cta: '423', description: 'Letras por Pagar', type: 'Balance' },
  { cta: '424', description: 'Honorarios por Pagar', type: 'Balance' },
  { cta: '44', description: 'CUENTAS POR PAGAR A LOS ACCIONISTAS Y DIRECTORES', type: 'Balance' },
  { cta: '441', description: 'Accionistas (socios)', type: 'Balance' },
  { cta: '45', description: 'OBLIGACIONES FINANCIERAS', type: 'Balance' },
  { cta: '451', description: 'Préstamos de Instituciones Financieras y Otras', type: 'Balance' },
  { cta: '46', description: 'CUENTAS POR PAGAR DIVERSAS - TERCEROS', type: 'Balance' },
  { cta: '461', description: 'Reclamaciones de terceros', type: 'Balance' },
  { cta: '469', description: 'Otras cuentas por pagar diversas', type: 'Balance' },

  // ──── PATRIMONIO ────
  { cta: '50', description: 'CAPITAL', type: 'Balance' },
  { cta: '501', description: 'Capital Social', type: 'Balance' },
  { cta: '5011', description: 'Acciones', type: 'Balance' },
  { cta: '5012', description: 'Participaciones', type: 'Balance' },
  { cta: '51', description: 'ACCIONES DE INVERSIÓN', type: 'Balance' },
  { cta: '511', description: 'Acciones de Inversión', type: 'Balance' },
  { cta: '52', description: 'CAPITAL ADICIONAL', type: 'Balance' },
  { cta: '56', description: 'RESULTADOS NO REALIZADOS', type: 'Balance' },
  { cta: '561', description: 'Excedente de Revaluación', type: 'Balance' },
  { cta: '57', description: 'EXCEDENTE DE REVALUACIÓN', type: 'Balance' },
  { cta: '58', description: 'RESERVAS', type: 'Balance' },
  { cta: '582', description: 'Reserva Legal', type: 'Balance' },
  { cta: '59', description: 'RESULTADOS ACUMULADOS', type: 'Balance' },
  { cta: '591', description: 'Utilidades no distribuidas', type: 'Balance' },
  { cta: '5911', description: 'Utilidades Acumuladas', type: 'Balance' },
  { cta: '592', description: 'Pérdidas acumuladas', type: 'Balance' },
  { cta: '5921', description: 'Pérdidas Acumuladas', type: 'Balance' },

  // ──── GASTOS POR NATURALEZA (CON AMARRES) ────
  { cta: '60', description: 'COMPRAS', type: 'Registro' },
  { cta: '601', description: 'Mercaderías', type: 'Registro', amarreDebe: '2011', amarreHaber: '6111' },
  { cta: '6011', description: 'Mercaderías manufacturadas', type: 'Registro', amarreDebe: '2011', amarreHaber: '6111' },
  { cta: '60111', description: 'Mercaderías manufacturadas - Importación', type: 'Registro', amarreDebe: '2011', amarreHaber: '6111' },
  { cta: '60112', description: 'Mercaderías manufacturadas - Mercado Local', type: 'Registro', amarreDebe: '2011', amarreHaber: '6111' },
  { cta: '602', description: 'Materias Primas', type: 'Registro', amarreDebe: '241', amarreHaber: '612' },
  { cta: '603', description: 'Materiales Auxiliares, Suministros y Repuestos', type: 'Registro', amarreDebe: '251', amarreHaber: '613' },
  { cta: '6031', description: 'Materiales auxiliares', type: 'Registro', amarreDebe: '251', amarreHaber: '613' },
  { cta: '6032', description: 'Suministros', type: 'Registro', amarreDebe: '252', amarreHaber: '613' },
  { cta: '61', description: 'VARIACIÓN DE INVENTARIOS', type: 'Registro' },
  { cta: '611', description: 'Mercaderías', type: 'Registro' },
  { cta: '6111', description: 'Mercaderías manufacturadas', type: 'Registro' },
  { cta: '61111', description: 'Mercaderías manufacturadas - Locales', type: 'Registro' },
  { cta: '61112', description: 'Mercaderías manufacturadas - Importadas', type: 'Registro' },
  { cta: '62', description: 'GASTOS DE PERSONAL Y DIRECTORES', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '621', description: 'Remuneraciones', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '622', description: 'Otras Remuneraciones', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '623', description: 'Indemnizaciones al personal', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '625', description: 'Otras remuneraciones', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '627', description: 'Seguridad y Previsión Social', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '6271', description: 'Régimen de prestaciones de salud', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '629', description: 'Beneficios sociales de los trabajadores', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '63', description: 'GASTOS DE SERVICIOS PRESTADOS POR TERCEROS', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '631', description: 'Transporte, correos y gastos de viaje', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '632', description: 'Asesoría y consultoría', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '6322', description: 'Honorarios, comisiones y corretajes', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '634', description: 'Mantenimiento y reparaciones', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '635', description: 'Alquileres', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '636', description: 'Servicios básicos', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '64', description: 'GASTOS POR TRIBUTOS', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '641', description: 'Impuesto a las transacciones financieras', type: 'Registro', reqCenCos: true, amarreDebe: '971', amarreHaber: '791' },
  { cta: '65', description: 'OTROS GASTOS DE GESTIÓN', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '659', description: 'Otros gastos de gestión', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '67', description: 'GASTOS FINANCIEROS', type: 'Registro', reqCenCos: true, amarreDebe: '971', amarreHaber: '791' },
  { cta: '676', description: 'Diferencia de cambio', type: 'Registro', reqCenCos: true, amarreDebe: '971', amarreHaber: '791' },
  { cta: '68', description: 'VALUACIÓN Y DETERIORO DE ACTIVOS Y PROVISIONES', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '681', description: 'Depreciación', type: 'Registro', reqCenCos: true, amarreDebe: '941', amarreHaber: '791' },
  { cta: '69', description: 'COSTO DE VENTAS', type: 'Registro' },
  { cta: '691', description: 'Mercaderías', type: 'Registro' },
  
  // ──── INGRESOS ────
  { cta: '70', description: 'VENTAS', type: 'Resultados' },
  { cta: '701', description: 'Ventas de mercaderías', type: 'Resultados' },
  { cta: '7011', description: 'Venta de mercaderías', type: 'Resultados' },
  { cta: '70111', description: 'Terceros (Venta Local)', type: 'Resultados' },
  { cta: '70112', description: 'Exportación', type: 'Resultados' },
  { cta: '702', description: 'Ventas de productos terminados', type: 'Resultados' },
  { cta: '704', description: 'Prestación de servicios', type: 'Resultados' },
  { cta: '75', description: 'OTROS INGRESOS DE GESTIÓN', type: 'Resultados' },
  { cta: '759', description: 'Otros ingresos de gestión', type: 'Resultados' },
  { cta: '76', description: 'GANANCIA POR MEDICIÓN DE ACTIVOS', type: 'Resultados' },
  { cta: '761', description: 'Ganancia por medición de activos no financieros', type: 'Resultados' },
  { cta: '77', description: 'INGRESOS FINANCIEROS', type: 'Resultados' },
  { cta: '771', description: 'Ganancia por inversiones financieras', type: 'Resultados' },
  { cta: '776', description: 'Diferencia en cambio', type: 'Resultados' },
  { cta: '779', description: 'Otros ingresos financieros', type: 'Resultados' },
  { cta: '78', description: 'CARGAS CUBIERTAS POR PROVISIONES', type: 'Resultados' },
  { cta: '781', description: 'Cargas cubiertas por provisiones', type: 'Resultados' },
  { cta: '79', description: 'CARGAS IMPUTABLES A CUENTAS DE COSTOS Y GASTOS', type: 'Registro' },
  { cta: '791', description: 'Cargas imputables a cuentas de costos y gastos', type: 'Registro' },

  // ──── CLASE 8: SALDOS INTERMEDIARIOS DE GESTIÓN ────
  { cta: '80', description: 'MARGEN COMERCIAL', type: 'Resultados' },
  { cta: '801', description: 'Margen comercial', type: 'Resultados' },
  { cta: '81', description: 'PRODUCCIÓN DEL EJERCICIO', type: 'Resultados' },
  { cta: '811', description: 'Producción de bienes', type: 'Resultados' },
  { cta: '812', description: 'Producción de servicios', type: 'Resultados' },
  { cta: '82', description: 'VALOR AGREGADO', type: 'Resultados' },
  { cta: '821', description: 'Valor agregado', type: 'Resultados' },
  { cta: '83', description: 'EXCEDENTE BRUTO DE EXPLOTACIÓN', type: 'Resultados' },
  { cta: '831', description: 'Excedente bruto (insuficiencia) de explotación', type: 'Resultados' },
  { cta: '84', description: 'RESULTADO DE EXPLOTACIÓN', type: 'Resultados' },
  { cta: '841', description: 'Resultado de explotación', type: 'Resultados' },
  { cta: '85', description: 'RESULTADO ANTES DE PARTICIPACIONES E IMPUESTOS', type: 'Resultados' },
  { cta: '851', description: 'Resultado antes de participaciones e impuestos', type: 'Resultados' },
  { cta: '87', description: 'PARTICIPACIONES DE LOS TRABAJADORES', type: 'Resultados' },
  { cta: '871', description: 'Participación de los trabajadores - corriente', type: 'Resultados' },
  { cta: '88', description: 'IMPUESTO A LA RENTA', type: 'Resultados' },
  { cta: '881', description: 'Impuesto a la renta - corriente', type: 'Resultados' },
  { cta: '89', description: 'DETERMINACIÓN DEL RESULTADO DEL EJERCICIO', type: 'Resultados' },
  { cta: '891', description: 'Utilidad', type: 'Resultados' },
  { cta: '892', description: 'Pérdida', type: 'Resultados' },

  // ──── COSTOS Y DESTINOS ────
  { cta: '90', description: 'COSTO DE PRODUCCIÓN (Opcional)', type: 'Registro' },
  { cta: '94', description: 'GASTOS ADMINISTRATIVOS', type: 'Registro' },
  { cta: '941', description: 'Gastos Administrativos', type: 'Registro' },
  { cta: '95', description: 'GASTOS DE VENTAS', type: 'Registro' },
  { cta: '951', description: 'Gastos de Ventas', type: 'Registro' },
  { cta: '97', description: 'GASTOS FINANCIEROS', type: 'Registro' },
  { cta: '971', description: 'Gastos Financieros', type: 'Registro' },
];
